### ISSUE TITLE
Monorepo example

### ISSUE THREAD

**Issue by jdinard** [semaphoreci-demos/semaphore-demo-workflows#1]
Hello,

Just trying to evaluate semaphore for a project with about 40 containerized microservices in a monorepo. The docs state that this is where monorepo examples live, but there don't seem to be any.

https://docs.semaphoreci.com/article/50-pipeline-yaml

**Comment by markoa** [comment]
Hi, sorry for non-direct link, the example is in the [monorepo branch](https://github.com/semaphoreci-demos/semaphore-demo-workflows/blob/monorepo/.semaphore/semaphore.yml) in this repo.

**Comment by jdinard** [comment]
Thats awesome. Thank you. 

Is there a way to define pipelines on a specific folder?

For example, our monorepo is structured like:

/root
        /service1
        /service2
        /service3

We don't want to build/trigger tests for service2 when someone commits a change that only impacts files in service1.

**Comment by markoa** [comment]
Yes, information about what has changed is in the git log.

We’ll provide some tips on doing this soon and I’ll make sure to let you
know.

**Comment by philippks** [comment]
Any news or hint about this @markoa? we've exactly the same use case:

> We don't want to build/trigger tests for service2 when someone commits a change that only impacts files in service1.

**Comment by markoa** [comment]
Not yet. We've looked into this but found that Semaphore is currently
missing some information in job context for the recipe to be feasible.
We're addressing that at the moment. I'll post when we have some news.

**Comment by steffenmllr** [comment]
@markoa that would be great - I'm looking to move a complex monorepo from github actions (too slow) to semaphore

**Comment by schmijos** [comment]
I'm on this as well. On CircleCI I could comfortably set the working directory. Should I just `cd` here all the time?

**Comment by markoa** [comment]
Update: we’re getting very close to shipping a condition for defining
workflows in monorepo context.

**Comment by markoa** [comment]
Josua, can you share some more context?

**Comment by schmijos** [comment]
In a monorepo I need to change to subdirectories by myself (compared to CircleCI where the working directory is configurable). I think my previous concern is a non-issue.

**Comment by markoa** [comment]
Folks, I'm happy to let you know that we have shipped monorepo support on Semaphore.

Please see [this documentation page](https://docs.semaphoreci.com/use-cases/building-monorepo-projects/) to get started, and let me know your impressions when you get a chance.

**Comment by schmijos** [comment]
Very cool how you keep listening to your customers!
Please also think about caching because the cache keys currently need to be isolated manually and I end up doing error prone things like this (actually I use `cache has_key` to prevent some errors):

```
- name: "Setup Customer Mobile App"
  commands:
    - cd web
    - cache restore mcweb-nodemodules-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock),mcweb-nodemodules-$SEMAPHORE_GIT_BRANCH,mcweb-nodemodules-master
    - yarn install
    - cache store mcweb-nodemodules-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock) node_modules
    - cd -
    - cd app
    - cache restore yarn-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock),yarn-$SEMAPHORE_GIT_BRANCH,yarn-master
    - cache restore mc-nodemodules-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock),mc-nodemodules-$SEMAPHORE_GIT_BRANCH,mc-nodemodules-master
    - yarn install
    - cache store yarn-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock) ~/.cache/yarn
    - cache store mc-nodemodules-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock) node_modules
…
- name: "Customer Mobile App Checks"
  …
    prologue:
      commands:
        - checkout
        - cd web
        - cache has_key mcweb-nodemodules-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock)
        - cache restore mcweb-nodemodules-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock)
        - cd -
        - cd app
        - cache has_key yarn-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock)
        - cache has_key mc-nodemodules-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock)
        - cache restore yarn-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock)
        - cache restore mc-nodemodules-$SEMAPHORE_GIT_BRANCH-$(checksum yarn.lock)
  …
```

I started with setups like these because I accidentally started overwriting `vendor/bundle` folders for multiple Ruby projects in the same monorepo when using the generic `cache store`.

**Comment by shiroyasha** [comment]
@schmijos Thank you for providing feedback about caching in monorepo contexts. We are designing improvements for monorepo caching.

One solution that we are investigating is to introduce namespaces into the cache, where each service could define its own namespace. 

For example: `cache store --namespace "mobile-app"` and `cache store --namespace "web-app"`.

Would this be a good solution to your project?

**Comment by schmijos** [comment]
@shiroyasha This would be exactly what we need ❤️

**Comment by LaloLoop** [comment]
Hello, I am having trouble with the documentation, as it states that we can change the agent per block defined in a monorepo. I have one [defined in my project](https://github.com/LaloLoop/Despenso/blob/c6a85d98142fde5be3cfc8f37ab9a3c967baf1c4/.semaphore/semaphore.yml) consisting of a python backend and iOS app. Whenever I try to set the iOS subfolder to use a different agent, I get the following error in my pipeline:

```bash
Error: [{"Schema does not allow additional properties.", "#/blocks/1/agent"}]
```

[The documentation](https://docs.semaphoreci.com/essentials/building-monorepo-projects/#an-example-monorepo-project-setup) shows that this should be possible, is this actually available right now in the platform or do I need to activate something to enable the beta features?

I saw that I can enable the agent per task, but that's not really ideal, since the iOS block will have more tasks added (building and shipping).

Please let me know if I can provide you with more information, and thank you for adding this!

**Comment by shiroyasha** [comment]
@LaloLoop Thanks for reporting. It's a mistake in our documentation.

Agent can be defined on the task level, not on the block level. Instead of:

``` yaml
  - name: Test iOS client
    dependencies: []
    run:
      when: "change_in('/ios/')"
    agent:
      machine:
        type: a1-standard-4
        os_image: macos-mojave-xcode11
    task:
      jobs:
        - commands:
            - checkout
            - cd ios
            - make test
```

It should be:


``` yaml
  - name: Test iOS client
    dependencies: []
    run:
      when: "change_in('/ios/')"
    task:
      agent:
        machine:
          type: a1-standard-4
          os_image: macos-mojave-xcode11
      jobs:
        - commands:
            - checkout
            - cd ios
            - make test
```
